# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
set encoding=utf8
set fileformats=unix,dos,mac

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

set smartindent
set number
set ic

# User specific aliases and functions
alias wldb='mysql -uroot -P3306 -p123456 -h 10.10.10.107 walle_online'
alias php=/home/xiaoju/php7/bin/php

# alanyuan definition
alias la='ll -a'

export PATH=/usr/local/git/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/jdk1.7.0_75/bin:/usr/local/go/bin:/home/xiaoju/bin

# golang dev
alias gopathhere='export GOPATH=$(pwd)'
#export PATH=$PATH
